catalogMode: prefer
cleanupUnusedCatalogs: true

shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^6.4.2
    bumpp: ^10.3.2
    eslint: ^9.39.1
    nuxt: ^4.1.3
    tsdown: ^0.17.0
    typescript: ^5.9.3
  integrations:
    '@nuxt/kit': ^4.1.3
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.1.3
  test:
    '@nuxt/test-utils': ^3.21.0
    vitest: ^4.0.15
  types:
    '@types/node': ^24.9.1
